services:
  frontend:
    container_name: journeytale-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm start
    depends_on:
      - backend
    networks:
      - journeytale-network

  backend:
    container_name: journeytale-backend
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@journeytale-db:5432/postgres
    depends_on:
      - db
    networks:
      - journeytale-network

  db:
    container_name: journeytale-db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - journeytale-network

networks:
  journeytale-network:
    driver: bridge

volumes:
  pgdata:
